-- CHANNELS
CREATE TABLE public.channels (
  id int generated by default as identity,
  inserted_at timestamp without time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp without time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  data jsonb DEFAULT null,
  slug text
);
ALTER TABLE public.channels REPLICA IDENTITY FULL;
ALTER publication supabase_realtime add table public.channels;