using System;
using Postgrest.Attributes;
using Postgrest.Models;
using Supabase;

namespace BlazorWebAssemblySupabaseTemplate.Dtos;

[Table("Todo")]
public class Todo : BaseModel
{
    [PrimaryKey("id", false)] // Key is Autogenerated
    public int Id { get; set; }

    [Column("Title")]
    public string? Title { get; set; }

}
