using System;
using Postgrest.Attributes;
using Supabase;

namespace SupabaseExample.Models
{
    [Table("channels")]
    public class Channel : SupabaseModel
    {
        [PrimaryKey("id", false)] // Key is Autogenerated
        public int Id { get; set; }

        [Column("inserted_at")]
        public DateTime InsertedAt { get; set; }

        [Column("slug")]
        public string Slug { get; set; }
    }
}
