-- Realtime E2E fixtures, folded in from realtime-csharp. Only the realtime-specific objects are
-- created here: the other sample tables its init.sql defined (users, channels, movie, person, ...)
-- already exist from the umbrella/postgrest migrations, so they are intentionally not duplicated.

-- todos: the table the postgres-changes delivery tests insert into. Must be in the realtime
-- publication with full replica identity so change events carry the row.
CREATE TYPE public.todo_status AS ENUM ('NOT STARTED', 'STARTED', 'COMPLETED');
create table public.todos
(
    id          bigint generated by default as identity not null,
    name        text                                    null,
    notes       text                                    null,
    done        boolean                                 null     default false,
    details     text                                    null,
    inserted_at timestamp without time zone             null     default now(),
    numbers     int[]                                   null,
    user_id     text                                    null,
    status      public.todo_status                      not null default 'NOT STARTED'::todo_status,
    constraint todos_pkey primary key (id)
) tablespace pg_default;
alter publication supabase_realtime add table public.todos;
alter table public.todos replica identity full;
grant select, insert, update, delete on public.todos to anon, authenticated, service_role;

-- Test fixture: emulates Supabase's realtime.send() so broadcast-replay tests can seed
-- messages into realtime.messages over REST. Local stack only.
CREATE OR REPLACE FUNCTION public.send(
    event text,
    topic text,
    private boolean
)
    RETURNS void
    LANGUAGE plpgsql
AS
$$
BEGIN
    BEGIN
        -- Scope the insert to the requested topic.
        EXECUTE format('SET LOCAL realtime.topic TO %L', topic);

        INSERT INTO realtime.messages (payload, event, topic, private, extension)
        VALUES (null, event, topic, private, 'broadcast');
    EXCEPTION
        WHEN OTHERS THEN
            RAISE WARNING 'ErrorSendingBroadcastMessage: %', SQLERRM;
    END;
END;
$$;
grant execute on function public.send(text, text, boolean) to anon, authenticated, service_role;

-- Test fixture: allow the broadcast seed inserts above. Local stack only.
CREATE POLICY messages_insert_all
    ON realtime.messages
    FOR INSERT
    TO PUBLIC
    WITH CHECK (true);
