-- channels

create table public.channels (
    id int generated by default as identity,
    inserted_at timestamp without time zone default timezone('utc'::text, now()) not null,
    update_at timestamp without time zone default timezone('utc'::text, now()) not null,
    data jsonb default null,
    slug text
);

alter table public.channels replica identity full;
alter publication supabase_realtime add table public.channels;