using Postgrest.Attributes;
using Postgrest.Models;

public class BaseModelApp : BaseModel
{
    [PrimaryKey("id", false)] // Key is Autogenerated
    public int Id { get; set; }

    [Column("SoftDelete")]
    public bool? SoftDeleted { get; set; }
    
    [Column("SoftDeletedAt")]
    public DateTime? SoftDeletedAt { get; set; }

}
