using System;
using Postgrest.Attributes;
using Postgrest.Models;
using Supabase;

namespace BlazorWebAssemblySupabaseTemplate.Dtos;

[Table("TodoPrivate")]
public class TodoPrivate : BaseModel
{
    [PrimaryKey("id", false)] // Key is Autogenerated
    public int Id { get; set; }

    [Column("title")]
    public string? Title { get; set; }

    [Column("user_id")]
    public string User_id { get; set; }
}
